info:
  name: 'M Podcasts'
  version: '1.0'
  description: 'Backend API for M Podcasts'

server:
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    context-path: /api/v1
jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

spring:
  application:
    name: MPodcasts
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  #mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'heinhtetag159666@gmail.com'
    password: 'cduuopaqdtxhkasu'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 43647900898-sej634mtaiuepujq5h9cs9ala2kda831.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          github:
            clientId: 4febcf42e5dab72c4b54
            clientSecret: 7f6769b3950a80f012a87062f6005867a1bc68b4
            scope:
              - user:email
              - read:user
          facebook:
            clientId: 1253548308673226
            clientSecret: 7e57a31ecb31d1c16422d1336ae61eae
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v17.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v17.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v17.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,picture.width(250).height(250)
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
g4:
  openapi:
    dev-url: 'http://localhost:8080'
    prod-url: 'https://g4backend.onrender.com'
firebase:
  bucket-name: 'm-podcats.appspot.com'
  audio-url: 'https://storage.googleapis.com/${firebase.bucket-name}/%s'
  service-account-path: 'firebase.json'
frontend:
  url: 'http://localhost:8888'
  redirect_url: '${frontend.url}/oauth2'