server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=UMPDB;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123@ace
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect

frontend:
  url: 'http://localhost:8888'
  redirect_url: '${frontend.url}/oauth2'